// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: internal/segmenttree/pb/segmenttree.proto

package segmenttreepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrentBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version    uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Balance    []byte `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"` // big-endian magnitude of big.Int
	StartBlock uint64 `protobuf:"varint,3,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
}

func (x *CurrentBalance) Reset() {
	*x = CurrentBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_segmenttree_pb_segmenttree_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrentBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentBalance) ProtoMessage() {}

func (x *CurrentBalance) ProtoReflect() protoreflect.Message {
	mi := &file_internal_segmenttree_pb_segmenttree_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentBalance.ProtoReflect.Descriptor instead.
func (*CurrentBalance) Descriptor() ([]byte, []int) {
	return file_internal_segmenttree_pb_segmenttree_proto_rawDescGZIP(), []int{0}
}

func (x *CurrentBalance) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CurrentBalance) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *CurrentBalance) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

type HistoricalBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Current  *CurrentBalance `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	EndBlock uint64          `protobuf:"varint,2,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
}

func (x *HistoricalBalance) Reset() {
	*x = HistoricalBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_segmenttree_pb_segmenttree_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoricalBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalBalance) ProtoMessage() {}

func (x *HistoricalBalance) ProtoReflect() protoreflect.Message {
	mi := &file_internal_segmenttree_pb_segmenttree_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalBalance.ProtoReflect.Descriptor instead.
func (*HistoricalBalance) Descriptor() ([]byte, []int) {
	return file_internal_segmenttree_pb_segmenttree_proto_rawDescGZIP(), []int{1}
}

func (x *HistoricalBalance) GetCurrent() *CurrentBalance {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *HistoricalBalance) GetEndBlock() uint64 {
	if x != nil {
		return x.EndBlock
	}
	return 0
}

// 32-byte hashes
type BatchTree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes [][]byte `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"` // each element is 32 bytes (common.Hash)
}

func (x *BatchTree) Reset() {
	*x = BatchTree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_segmenttree_pb_segmenttree_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTree) ProtoMessage() {}

func (x *BatchTree) ProtoReflect() protoreflect.Message {
	mi := &file_internal_segmenttree_pb_segmenttree_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTree.ProtoReflect.Descriptor instead.
func (*BatchTree) Descriptor() ([]byte, []int) {
	return file_internal_segmenttree_pb_segmenttree_proto_rawDescGZIP(), []int{2}
}

func (x *BatchTree) GetNodes() [][]byte {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type LXBatchTree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layers []*BatchTree `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty"` // index 0..MaxLayer-1
}

func (x *LXBatchTree) Reset() {
	*x = LXBatchTree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_segmenttree_pb_segmenttree_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LXBatchTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LXBatchTree) ProtoMessage() {}

func (x *LXBatchTree) ProtoReflect() protoreflect.Message {
	mi := &file_internal_segmenttree_pb_segmenttree_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LXBatchTree.ProtoReflect.Descriptor instead.
func (*LXBatchTree) Descriptor() ([]byte, []int) {
	return file_internal_segmenttree_pb_segmenttree_proto_rawDescGZIP(), []int{3}
}

func (x *LXBatchTree) GetLayers() []*BatchTree {
	if x != nil {
		return x.Layers
	}
	return nil
}

// 48-byte compressed KZG digest
type KZGDigest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Digest []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"` // 48 bytes
}

func (x *KZGDigest) Reset() {
	*x = KZGDigest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_segmenttree_pb_segmenttree_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KZGDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KZGDigest) ProtoMessage() {}

func (x *KZGDigest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_segmenttree_pb_segmenttree_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KZGDigest.ProtoReflect.Descriptor instead.
func (*KZGDigest) Descriptor() ([]byte, []int) {
	return file_internal_segmenttree_pb_segmenttree_proto_rawDescGZIP(), []int{4}
}

func (x *KZGDigest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type LXBatchCommitment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layers []*KZGDigest `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty"` // index 0..MaxLayer-1
}

func (x *LXBatchCommitment) Reset() {
	*x = LXBatchCommitment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_segmenttree_pb_segmenttree_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LXBatchCommitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LXBatchCommitment) ProtoMessage() {}

func (x *LXBatchCommitment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_segmenttree_pb_segmenttree_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LXBatchCommitment.ProtoReflect.Descriptor instead.
func (*LXBatchCommitment) Descriptor() ([]byte, []int) {
	return file_internal_segmenttree_pb_segmenttree_proto_rawDescGZIP(), []int{5}
}

func (x *LXBatchCommitment) GetLayers() []*KZGDigest {
	if x != nil {
		return x.Layers
	}
	return nil
}

type AccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account                  []byte             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"` // 20 bytes (common.Address)
	CurrentBalance           *CurrentBalance    `protobuf:"bytes,2,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	CurrentLxBatchTree       *LXBatchTree       `protobuf:"bytes,3,opt,name=current_lx_batch_tree,json=currentLxBatchTree,proto3" json:"current_lx_batch_tree,omitempty"`
	CurrentLxBatchCommitment *LXBatchCommitment `protobuf:"bytes,4,opt,name=current_lx_batch_commitment,json=currentLxBatchCommitment,proto3" json:"current_lx_batch_commitment,omitempty"`
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_segmenttree_pb_segmenttree_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_segmenttree_pb_segmenttree_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_internal_segmenttree_pb_segmenttree_proto_rawDescGZIP(), []int{6}
}

func (x *AccountInfo) GetAccount() []byte {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AccountInfo) GetCurrentBalance() *CurrentBalance {
	if x != nil {
		return x.CurrentBalance
	}
	return nil
}

func (x *AccountInfo) GetCurrentLxBatchTree() *LXBatchTree {
	if x != nil {
		return x.CurrentLxBatchTree
	}
	return nil
}

func (x *AccountInfo) GetCurrentLxBatchCommitment() *LXBatchCommitment {
	if x != nil {
		return x.CurrentLxBatchCommitment
	}
	return nil
}

var File_internal_segmenttree_pb_segmenttree_proto protoreflect.FileDescriptor

var file_internal_segmenttree_pb_segmenttree_proto_rawDesc = []byte{
	0x0a, 0x29, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x74, 0x72, 0x65, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x65, 0x0a, 0x0e, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x22, 0x6a, 0x0a, 0x11, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x21,
	0x0a, 0x09, 0x42, 0x61, 0x74, 0x63, 0x68, 0x54, 0x72, 0x65, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x22, 0x40, 0x0a, 0x0b, 0x4c, 0x58, 0x42, 0x61, 0x74, 0x63, 0x68, 0x54, 0x72, 0x65, 0x65,
	0x12, 0x31, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x54, 0x72, 0x65, 0x65, 0x52, 0x06, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x22, 0x23, 0x0a, 0x09, 0x4b, 0x5a, 0x47, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x11, 0x4c, 0x58, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x31, 0x0a,
	0x06, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4b,
	0x5a, 0x47, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x22, 0xa2, 0x02, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x47, 0x0a, 0x0f, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x74, 0x72, 0x65,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x15, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6c,
	0x78, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x74, 0x72, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x74, 0x72, 0x65, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x58, 0x42, 0x61, 0x74, 0x63, 0x68, 0x54, 0x72, 0x65, 0x65, 0x52,
	0x12, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4c, 0x78, 0x42, 0x61, 0x74, 0x63, 0x68, 0x54,
	0x72, 0x65, 0x65, 0x12, 0x60, 0x0a, 0x1b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6c,
	0x78, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x58, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x18, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x4c, 0x78, 0x42, 0x61, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x65, 0x70, 0x61, 0x6c, 0x38, 0x30, 0x6d, 0x2f, 0x73, 0x61, 0x6d,
	0x75, 0x72, 0x61, 0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x74, 0x72, 0x65, 0x65, 0x2f, 0x70, 0x62, 0x3b, 0x73, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x74, 0x72, 0x65, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_segmenttree_pb_segmenttree_proto_rawDescOnce sync.Once
	file_internal_segmenttree_pb_segmenttree_proto_rawDescData = file_internal_segmenttree_pb_segmenttree_proto_rawDesc
)

func file_internal_segmenttree_pb_segmenttree_proto_rawDescGZIP() []byte {
	file_internal_segmenttree_pb_segmenttree_proto_rawDescOnce.Do(func() {
		file_internal_segmenttree_pb_segmenttree_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_segmenttree_pb_segmenttree_proto_rawDescData)
	})
	return file_internal_segmenttree_pb_segmenttree_proto_rawDescData
}

var file_internal_segmenttree_pb_segmenttree_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_segmenttree_pb_segmenttree_proto_goTypes = []any{
	(*CurrentBalance)(nil),    // 0: segmenttree.v1.CurrentBalance
	(*HistoricalBalance)(nil), // 1: segmenttree.v1.HistoricalBalance
	(*BatchTree)(nil),         // 2: segmenttree.v1.BatchTree
	(*LXBatchTree)(nil),       // 3: segmenttree.v1.LXBatchTree
	(*KZGDigest)(nil),         // 4: segmenttree.v1.KZGDigest
	(*LXBatchCommitment)(nil), // 5: segmenttree.v1.LXBatchCommitment
	(*AccountInfo)(nil),       // 6: segmenttree.v1.AccountInfo
}
var file_internal_segmenttree_pb_segmenttree_proto_depIdxs = []int32{
	0, // 0: segmenttree.v1.HistoricalBalance.current:type_name -> segmenttree.v1.CurrentBalance
	2, // 1: segmenttree.v1.LXBatchTree.layers:type_name -> segmenttree.v1.BatchTree
	4, // 2: segmenttree.v1.LXBatchCommitment.layers:type_name -> segmenttree.v1.KZGDigest
	0, // 3: segmenttree.v1.AccountInfo.current_balance:type_name -> segmenttree.v1.CurrentBalance
	3, // 4: segmenttree.v1.AccountInfo.current_lx_batch_tree:type_name -> segmenttree.v1.LXBatchTree
	5, // 5: segmenttree.v1.AccountInfo.current_lx_batch_commitment:type_name -> segmenttree.v1.LXBatchCommitment
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_segmenttree_pb_segmenttree_proto_init() }
func file_internal_segmenttree_pb_segmenttree_proto_init() {
	if File_internal_segmenttree_pb_segmenttree_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_segmenttree_pb_segmenttree_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CurrentBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_segmenttree_pb_segmenttree_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HistoricalBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_segmenttree_pb_segmenttree_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BatchTree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_segmenttree_pb_segmenttree_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LXBatchTree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_segmenttree_pb_segmenttree_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*KZGDigest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_segmenttree_pb_segmenttree_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LXBatchCommitment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_segmenttree_pb_segmenttree_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*AccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_segmenttree_pb_segmenttree_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_segmenttree_pb_segmenttree_proto_goTypes,
		DependencyIndexes: file_internal_segmenttree_pb_segmenttree_proto_depIdxs,
		MessageInfos:      file_internal_segmenttree_pb_segmenttree_proto_msgTypes,
	}.Build()
	File_internal_segmenttree_pb_segmenttree_proto = out.File
	file_internal_segmenttree_pb_segmenttree_proto_rawDesc = nil
	file_internal_segmenttree_pb_segmenttree_proto_goTypes = nil
	file_internal_segmenttree_pb_segmenttree_proto_depIdxs = nil
}
