// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.0
// source: api/proto/v1/proof_service.proto

package proofpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VerkleProofService_GetRangeProof_FullMethodName = "/baseline.api.v1.VerkleProofService/GetRangeProof"
)

// VerkleProofServiceClient is the client API for VerkleProofService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VerkleProofService provides Verkle tree proof generation for account balances.
type VerkleProofServiceClient interface {
	// GetRangeProof streams account proofs for each block in the given range.
	GetRangeProof(ctx context.Context, in *GetRangeProofRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockProof], error)
}

type verkleProofServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVerkleProofServiceClient(cc grpc.ClientConnInterface) VerkleProofServiceClient {
	return &verkleProofServiceClient{cc}
}

func (c *verkleProofServiceClient) GetRangeProof(ctx context.Context, in *GetRangeProofRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockProof], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VerkleProofService_ServiceDesc.Streams[0], VerkleProofService_GetRangeProof_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRangeProofRequest, BlockProof]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VerkleProofService_GetRangeProofClient = grpc.ServerStreamingClient[BlockProof]

// VerkleProofServiceServer is the server API for VerkleProofService service.
// All implementations must embed UnimplementedVerkleProofServiceServer
// for forward compatibility.
//
// VerkleProofService provides Verkle tree proof generation for account balances.
type VerkleProofServiceServer interface {
	// GetRangeProof streams account proofs for each block in the given range.
	GetRangeProof(*GetRangeProofRequest, grpc.ServerStreamingServer[BlockProof]) error
	mustEmbedUnimplementedVerkleProofServiceServer()
}

// UnimplementedVerkleProofServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerkleProofServiceServer struct{}

func (UnimplementedVerkleProofServiceServer) GetRangeProof(*GetRangeProofRequest, grpc.ServerStreamingServer[BlockProof]) error {
	return status.Error(codes.Unimplemented, "method GetRangeProof not implemented")
}
func (UnimplementedVerkleProofServiceServer) mustEmbedUnimplementedVerkleProofServiceServer() {}
func (UnimplementedVerkleProofServiceServer) testEmbeddedByValue()                            {}

// UnsafeVerkleProofServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerkleProofServiceServer will
// result in compilation errors.
type UnsafeVerkleProofServiceServer interface {
	mustEmbedUnimplementedVerkleProofServiceServer()
}

func RegisterVerkleProofServiceServer(s grpc.ServiceRegistrar, srv VerkleProofServiceServer) {
	// If the following call panics, it indicates UnimplementedVerkleProofServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VerkleProofService_ServiceDesc, srv)
}

func _VerkleProofService_GetRangeProof_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRangeProofRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VerkleProofServiceServer).GetRangeProof(m, &grpc.GenericServerStream[GetRangeProofRequest, BlockProof]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VerkleProofService_GetRangeProofServer = grpc.ServerStreamingServer[BlockProof]

// VerkleProofService_ServiceDesc is the grpc.ServiceDesc for VerkleProofService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerkleProofService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "baseline.api.v1.VerkleProofService",
	HandlerType: (*VerkleProofServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRangeProof",
			Handler:       _VerkleProofService_GetRangeProof_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/v1/proof_service.proto",
}
