// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: api/proto/v1/proof_service.proto

package proofpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProofService_GetRangeProof_FullMethodName = "/baseline.api.v1.ProofService/GetRangeProof"
)

// ProofServiceClient is the client API for ProofService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProofService provides Merkle Patricia Trie proof generation for account balances.
type ProofServiceClient interface {
	// GetRangeProof streams account proofs for each block in the given range.
	GetRangeProof(ctx context.Context, in *GetRangeProofRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockProof], error)
}

type proofServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProofServiceClient(cc grpc.ClientConnInterface) ProofServiceClient {
	return &proofServiceClient{cc}
}

func (c *proofServiceClient) GetRangeProof(ctx context.Context, in *GetRangeProofRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockProof], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProofService_ServiceDesc.Streams[0], ProofService_GetRangeProof_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRangeProofRequest, BlockProof]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProofService_GetRangeProofClient = grpc.ServerStreamingClient[BlockProof]

// ProofServiceServer is the server API for ProofService service.
// All implementations must embed UnimplementedProofServiceServer
// for forward compatibility.
//
// ProofService provides Merkle Patricia Trie proof generation for account balances.
type ProofServiceServer interface {
	// GetRangeProof streams account proofs for each block in the given range.
	GetRangeProof(*GetRangeProofRequest, grpc.ServerStreamingServer[BlockProof]) error
	mustEmbedUnimplementedProofServiceServer()
}

// UnimplementedProofServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProofServiceServer struct{}

func (UnimplementedProofServiceServer) GetRangeProof(*GetRangeProofRequest, grpc.ServerStreamingServer[BlockProof]) error {
	return status.Error(codes.Unimplemented, "method GetRangeProof not implemented")
}
func (UnimplementedProofServiceServer) mustEmbedUnimplementedProofServiceServer() {}
func (UnimplementedProofServiceServer) testEmbeddedByValue()                      {}

// UnsafeProofServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProofServiceServer will
// result in compilation errors.
type UnsafeProofServiceServer interface {
	mustEmbedUnimplementedProofServiceServer()
}

func RegisterProofServiceServer(s grpc.ServiceRegistrar, srv ProofServiceServer) {
	// If the following call panics, it indicates UnimplementedProofServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProofService_ServiceDesc, srv)
}

func _ProofService_GetRangeProof_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRangeProofRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProofServiceServer).GetRangeProof(m, &grpc.GenericServerStream[GetRangeProofRequest, BlockProof]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProofService_GetRangeProofServer = grpc.ServerStreamingServer[BlockProof]

// ProofService_ServiceDesc is the grpc.ServiceDesc for ProofService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProofService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "baseline.api.v1.ProofService",
	HandlerType: (*ProofServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRangeProof",
			Handler:       _ProofService_GetRangeProof_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/v1/proof_service.proto",
}
