// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/v1/proof_service.proto

package proofpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRangeProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	StartBlock    uint64                 `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock      uint64                 `protobuf:"varint,3,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRangeProofRequest) Reset() {
	*x = GetRangeProofRequest{}
	mi := &file_api_proto_v1_proof_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRangeProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRangeProofRequest) ProtoMessage() {}

func (x *GetRangeProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_proof_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRangeProofRequest.ProtoReflect.Descriptor instead.
func (*GetRangeProofRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_proof_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRangeProofRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GetRangeProofRequest) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *GetRangeProofRequest) GetEndBlock() uint64 {
	if x != nil {
		return x.EndBlock
	}
	return 0
}

// BlockProof is a single eth_getProof-style account proof at one block.
type BlockProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,2,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	AccountProof  [][]byte               `protobuf:"bytes,3,rep,name=account_proof,json=accountProof,proto3" json:"account_proof,omitempty"` // RLP-encoded trie nodes
	Balance       []byte                 `protobuf:"bytes,4,opt,name=balance,proto3" json:"balance,omitempty"`                               // big-endian big.Int
	Nonce         uint64                 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Exists        bool                   `protobuf:"varint,6,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockProof) Reset() {
	*x = BlockProof{}
	mi := &file_api_proto_v1_proof_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockProof) ProtoMessage() {}

func (x *BlockProof) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_proof_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockProof.ProtoReflect.Descriptor instead.
func (*BlockProof) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_proof_service_proto_rawDescGZIP(), []int{1}
}

func (x *BlockProof) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BlockProof) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BlockProof) GetAccountProof() [][]byte {
	if x != nil {
		return x.AccountProof
	}
	return nil
}

func (x *BlockProof) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *BlockProof) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *BlockProof) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_api_proto_v1_proof_service_proto protoreflect.FileDescriptor

const file_api_proto_v1_proof_service_proto_rawDesc = "" +
	"\n" +
	" api/proto/v1/proof_service.proto\x12\x0fbaseline.api.v1\"n\n" +
	"\x14GetRangeProofRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1f\n" +
	"\vstart_block\x18\x02 \x01(\x04R\n" +
	"startBlock\x12\x1b\n" +
	"\tend_block\x18\x03 \x01(\x04R\bendBlock\"\xbb\x01\n" +
	"\n" +
	"BlockProof\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"state_root\x18\x02 \x01(\fR\tstateRoot\x12#\n" +
	"\raccount_proof\x18\x03 \x03(\fR\faccountProof\x12\x18\n" +
	"\abalance\x18\x04 \x01(\fR\abalance\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x04R\x05nonce\x12\x16\n" +
	"\x06exists\x18\x06 \x01(\bR\x06exists2e\n" +
	"\fProofService\x12U\n" +
	"\rGetRangeProof\x12%.baseline.api.v1.GetRangeProofRequest\x1a\x1b.baseline.api.v1.BlockProof0\x01B:Z8github.com/nepal80m/baseline-merkle/api/proto/v1;proofpbb\x06proto3"

var (
	file_api_proto_v1_proof_service_proto_rawDescOnce sync.Once
	file_api_proto_v1_proof_service_proto_rawDescData []byte
)

func file_api_proto_v1_proof_service_proto_rawDescGZIP() []byte {
	file_api_proto_v1_proof_service_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_proof_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_proof_service_proto_rawDesc), len(file_api_proto_v1_proof_service_proto_rawDesc)))
	})
	return file_api_proto_v1_proof_service_proto_rawDescData
}

var file_api_proto_v1_proof_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_proof_service_proto_goTypes = []any{
	(*GetRangeProofRequest)(nil), // 0: baseline.api.v1.GetRangeProofRequest
	(*BlockProof)(nil),           // 1: baseline.api.v1.BlockProof
}
var file_api_proto_v1_proof_service_proto_depIdxs = []int32{
	0, // 0: baseline.api.v1.ProofService.GetRangeProof:input_type -> baseline.api.v1.GetRangeProofRequest
	1, // 1: baseline.api.v1.ProofService.GetRangeProof:output_type -> baseline.api.v1.BlockProof
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_proof_service_proto_init() }
func file_api_proto_v1_proof_service_proto_init() {
	if File_api_proto_v1_proof_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_proof_service_proto_rawDesc), len(file_api_proto_v1_proof_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_proof_service_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_proof_service_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_proof_service_proto_msgTypes,
	}.Build()
	File_api_proto_v1_proof_service_proto = out.File
	file_api_proto_v1_proof_service_proto_goTypes = nil
	file_api_proto_v1_proof_service_proto_depIdxs = nil
}
