// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: api/proto/v1/proof_service.proto

package proofpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProofService_GetProof_FullMethodName       = "/samurai.api.v1.ProofService/GetProof"
	ProofService_GetProofStream_FullMethodName = "/samurai.api.v1.ProofService/GetProofStream"
)

// ProofServiceClient is the client API for ProofService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProofService provides cryptographic proof generation for account balance history.
type ProofServiceClient interface {
	// GetProof generates range proofs for a given account and block range.
	GetProof(ctx context.Context, in *GetProofRequest, opts ...grpc.CallOption) (*GetProofResponse, error)
	// GetProofStream streams range proofs for a given account and block range.
	GetProofStream(ctx context.Context, in *GetProofRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetProofResponse], error)
}

type proofServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProofServiceClient(cc grpc.ClientConnInterface) ProofServiceClient {
	return &proofServiceClient{cc}
}

func (c *proofServiceClient) GetProof(ctx context.Context, in *GetProofRequest, opts ...grpc.CallOption) (*GetProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProofResponse)
	err := c.cc.Invoke(ctx, ProofService_GetProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proofServiceClient) GetProofStream(ctx context.Context, in *GetProofRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetProofResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProofService_ServiceDesc.Streams[0], ProofService_GetProofStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetProofRequest, GetProofResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProofService_GetProofStreamClient = grpc.ServerStreamingClient[GetProofResponse]

// ProofServiceServer is the server API for ProofService service.
// All implementations must embed UnimplementedProofServiceServer
// for forward compatibility.
//
// ProofService provides cryptographic proof generation for account balance history.
type ProofServiceServer interface {
	// GetProof generates range proofs for a given account and block range.
	GetProof(context.Context, *GetProofRequest) (*GetProofResponse, error)
	// GetProofStream streams range proofs for a given account and block range.
	GetProofStream(*GetProofRequest, grpc.ServerStreamingServer[GetProofResponse]) error
	mustEmbedUnimplementedProofServiceServer()
}

// UnimplementedProofServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProofServiceServer struct{}

func (UnimplementedProofServiceServer) GetProof(context.Context, *GetProofRequest) (*GetProofResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProof not implemented")
}
func (UnimplementedProofServiceServer) GetProofStream(*GetProofRequest, grpc.ServerStreamingServer[GetProofResponse]) error {
	return status.Error(codes.Unimplemented, "method GetProofStream not implemented")
}
func (UnimplementedProofServiceServer) mustEmbedUnimplementedProofServiceServer() {}
func (UnimplementedProofServiceServer) testEmbeddedByValue()                      {}

// UnsafeProofServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProofServiceServer will
// result in compilation errors.
type UnsafeProofServiceServer interface {
	mustEmbedUnimplementedProofServiceServer()
}

func RegisterProofServiceServer(s grpc.ServiceRegistrar, srv ProofServiceServer) {
	// If the following call panics, it indicates UnimplementedProofServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProofService_ServiceDesc, srv)
}

func _ProofService_GetProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProofServiceServer).GetProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProofService_GetProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProofServiceServer).GetProof(ctx, req.(*GetProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProofService_GetProofStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetProofRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProofServiceServer).GetProofStream(m, &grpc.GenericServerStream[GetProofRequest, GetProofResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProofService_GetProofStreamServer = grpc.ServerStreamingServer[GetProofResponse]

// ProofService_ServiceDesc is the grpc.ServiceDesc for ProofService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProofService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "samurai.api.v1.ProofService",
	HandlerType: (*ProofServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProof",
			Handler:    _ProofService_GetProof_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetProofStream",
			Handler:       _ProofService_GetProofStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/v1/proof_service.proto",
}
