// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/samurai/v1/proof_service.proto

package proofpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetProofRequest specifies the account and block range for proof generation.
type GetProofRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ethereum account address (20 bytes, hex-encoded without 0x prefix or with).
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// Starting block number (inclusive).
	StartBlock uint64 `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	// Ending block number (inclusive).
	EndBlock      uint64 `protobuf:"varint,3,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofRequest) Reset() {
	*x = GetProofRequest{}
	mi := &file_api_proto_samurai_v1_proof_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofRequest) ProtoMessage() {}

func (x *GetProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_samurai_v1_proof_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofRequest.ProtoReflect.Descriptor instead.
func (*GetProofRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_samurai_v1_proof_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetProofRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GetProofRequest) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *GetProofRequest) GetEndBlock() uint64 {
	if x != nil {
		return x.EndBlock
	}
	return 0
}

// GetProofResponse contains the generated proofs and balance information.
type GetProofResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of range proofs covering the requested block range.
	RangeProofs []*RangeProof `protobuf:"bytes,1,rep,name=range_proofs,json=rangeProofs,proto3" json:"range_proofs,omitempty"`
	// List of historical balance entries for the range.
	BalanceInfos []*BalanceInfo `protobuf:"bytes,2,rep,name=balance_infos,json=balanceInfos,proto3" json:"balance_infos,omitempty"`
	// Time taken to generate proofs in nanoseconds.
	ProofgenDurationNs int64 `protobuf:"varint,3,opt,name=proofgen_duration_ns,json=proofgenDurationNs,proto3" json:"proofgen_duration_ns,omitempty"`
	// MPT membership proof nodes (raw trie nodes, in traversal order).
	MptProofNodes [][]byte `protobuf:"bytes,4,rep,name=mpt_proof_nodes,json=mptProofNodes,proto3" json:"mpt_proof_nodes,omitempty"`
	// Current balance of the account (big-endian bytes of big.Int).
	CurrentBalance []byte `protobuf:"bytes,5,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	// The block number for which the MPT proof is valid.
	MptBlockNumber uint64 `protobuf:"varint,6,opt,name=mpt_block_number,json=mptBlockNumber,proto3" json:"mpt_block_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProofResponse) Reset() {
	*x = GetProofResponse{}
	mi := &file_api_proto_samurai_v1_proof_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofResponse) ProtoMessage() {}

func (x *GetProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_samurai_v1_proof_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofResponse.ProtoReflect.Descriptor instead.
func (*GetProofResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_samurai_v1_proof_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetProofResponse) GetRangeProofs() []*RangeProof {
	if x != nil {
		return x.RangeProofs
	}
	return nil
}

func (x *GetProofResponse) GetBalanceInfos() []*BalanceInfo {
	if x != nil {
		return x.BalanceInfos
	}
	return nil
}

func (x *GetProofResponse) GetProofgenDurationNs() int64 {
	if x != nil {
		return x.ProofgenDurationNs
	}
	return 0
}

func (x *GetProofResponse) GetMptProofNodes() [][]byte {
	if x != nil {
		return x.MptProofNodes
	}
	return nil
}

func (x *GetProofResponse) GetCurrentBalance() []byte {
	if x != nil {
		return x.CurrentBalance
	}
	return nil
}

func (x *GetProofResponse) GetMptBlockNumber() uint64 {
	if x != nil {
		return x.MptBlockNumber
	}
	return 0
}

// RangeProof represents a cryptographic proof for a range of blocks.
type RangeProof struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Layer in the commitment tree (1 to MaxLayer).
	Layer int32 `protobuf:"varint,1,opt,name=layer,proto3" json:"layer,omitempty"`
	// Index within the layer.
	Idx int32 `protobuf:"varint,2,opt,name=idx,proto3" json:"idx,omitempty"`
	// KZG commitment (48 bytes, compressed G1 point).
	Commitment []byte `protobuf:"bytes,3,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// KZG proof (48 bytes, compressed G1 point).
	Proof []byte `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
	// Block range covered by this proof.
	BlockRange *BlockRange `protobuf:"bytes,5,opt,name=block_range,json=blockRange,proto3" json:"block_range,omitempty"`
	// Indices of dependent commitments from lower layers.
	DependentCommitments []int32 `protobuf:"varint,6,rep,packed,name=dependent_commitments,json=dependentCommitments,proto3" json:"dependent_commitments,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RangeProof) Reset() {
	*x = RangeProof{}
	mi := &file_api_proto_samurai_v1_proof_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeProof) ProtoMessage() {}

func (x *RangeProof) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_samurai_v1_proof_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeProof.ProtoReflect.Descriptor instead.
func (*RangeProof) Descriptor() ([]byte, []int) {
	return file_api_proto_samurai_v1_proof_service_proto_rawDescGZIP(), []int{2}
}

func (x *RangeProof) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *RangeProof) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *RangeProof) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *RangeProof) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *RangeProof) GetBlockRange() *BlockRange {
	if x != nil {
		return x.BlockRange
	}
	return nil
}

func (x *RangeProof) GetDependentCommitments() []int32 {
	if x != nil {
		return x.DependentCommitments
	}
	return nil
}

// BlockRange represents a contiguous range of blocks.
type BlockRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int32                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           int32                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRange) Reset() {
	*x = BlockRange{}
	mi := &file_api_proto_samurai_v1_proof_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRange) ProtoMessage() {}

func (x *BlockRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_samurai_v1_proof_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRange.ProtoReflect.Descriptor instead.
func (*BlockRange) Descriptor() ([]byte, []int) {
	return file_api_proto_samurai_v1_proof_service_proto_rawDescGZIP(), []int{3}
}

func (x *BlockRange) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *BlockRange) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

// BalanceInfo represents historical balance information for an account.
type BalanceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version number in the commitment tree.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Block number when this balance became active.
	StartBlock uint64 `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	// Block number when this balance was superseded (inclusive).
	EndBlock uint64 `protobuf:"varint,3,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	// Balance value (big-endian bytes of big.Int).
	Balance       []byte `protobuf:"bytes,4,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceInfo) Reset() {
	*x = BalanceInfo{}
	mi := &file_api_proto_samurai_v1_proof_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceInfo) ProtoMessage() {}

func (x *BalanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_samurai_v1_proof_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceInfo.ProtoReflect.Descriptor instead.
func (*BalanceInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_samurai_v1_proof_service_proto_rawDescGZIP(), []int{4}
}

func (x *BalanceInfo) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BalanceInfo) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *BalanceInfo) GetEndBlock() uint64 {
	if x != nil {
		return x.EndBlock
	}
	return 0
}

func (x *BalanceInfo) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

// GetInfoRequest is empty — no parameters needed.
type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_api_proto_samurai_v1_proof_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_samurai_v1_proof_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_samurai_v1_proof_service_proto_rawDescGZIP(), []int{5}
}

// GetInfoResponse returns the latest processed block and state root.
type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatestBlock   uint64                 `protobuf:"varint,1,opt,name=latest_block,json=latestBlock,proto3" json:"latest_block,omitempty"`
	StateRoot     string                 `protobuf:"bytes,2,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_api_proto_samurai_v1_proof_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_samurai_v1_proof_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_samurai_v1_proof_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetInfoResponse) GetLatestBlock() uint64 {
	if x != nil {
		return x.LatestBlock
	}
	return 0
}

func (x *GetInfoResponse) GetStateRoot() string {
	if x != nil {
		return x.StateRoot
	}
	return ""
}

var File_api_proto_samurai_v1_proof_service_proto protoreflect.FileDescriptor

const file_api_proto_samurai_v1_proof_service_proto_rawDesc = "" +
	"\n" +
	"(api/proto/samurai/v1/proof_service.proto\x12\x0esamurai.api.v1\"i\n" +
	"\x0fGetProofRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1f\n" +
	"\vstart_block\x18\x02 \x01(\x04R\n" +
	"startBlock\x12\x1b\n" +
	"\tend_block\x18\x03 \x01(\x04R\bendBlock\"\xc0\x02\n" +
	"\x10GetProofResponse\x12=\n" +
	"\frange_proofs\x18\x01 \x03(\v2\x1a.samurai.api.v1.RangeProofR\vrangeProofs\x12@\n" +
	"\rbalance_infos\x18\x02 \x03(\v2\x1b.samurai.api.v1.BalanceInfoR\fbalanceInfos\x120\n" +
	"\x14proofgen_duration_ns\x18\x03 \x01(\x03R\x12proofgenDurationNs\x12&\n" +
	"\x0fmpt_proof_nodes\x18\x04 \x03(\fR\rmptProofNodes\x12'\n" +
	"\x0fcurrent_balance\x18\x05 \x01(\fR\x0ecurrentBalance\x12(\n" +
	"\x10mpt_block_number\x18\x06 \x01(\x04R\x0emptBlockNumber\"\xdc\x01\n" +
	"\n" +
	"RangeProof\x12\x14\n" +
	"\x05layer\x18\x01 \x01(\x05R\x05layer\x12\x10\n" +
	"\x03idx\x18\x02 \x01(\x05R\x03idx\x12\x1e\n" +
	"\n" +
	"commitment\x18\x03 \x01(\fR\n" +
	"commitment\x12\x14\n" +
	"\x05proof\x18\x04 \x01(\fR\x05proof\x12;\n" +
	"\vblock_range\x18\x05 \x01(\v2\x1a.samurai.api.v1.BlockRangeR\n" +
	"blockRange\x123\n" +
	"\x15dependent_commitments\x18\x06 \x03(\x05R\x14dependentCommitments\"4\n" +
	"\n" +
	"BlockRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x05R\x03end\"\x7f\n" +
	"\vBalanceInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1f\n" +
	"\vstart_block\x18\x02 \x01(\x04R\n" +
	"startBlock\x12\x1b\n" +
	"\tend_block\x18\x03 \x01(\x04R\bendBlock\x12\x18\n" +
	"\abalance\x18\x04 \x01(\fR\abalance\"\x10\n" +
	"\x0eGetInfoRequest\"S\n" +
	"\x0fGetInfoResponse\x12!\n" +
	"\flatest_block\x18\x01 \x01(\x04R\vlatestBlock\x12\x1d\n" +
	"\n" +
	"state_root\x18\x02 \x01(\tR\tstateRoot2\xda\x02\n" +
	"\fProofService\x12M\n" +
	"\bGetProof\x12\x1f.samurai.api.v1.GetProofRequest\x1a .samurai.api.v1.GetProofResponse\x12U\n" +
	"\x0eGetProofStream\x12\x1f.samurai.api.v1.GetProofRequest\x1a .samurai.api.v1.GetProofResponse0\x01\x12X\n" +
	"\x11GetOldProofStream\x12\x1f.samurai.api.v1.GetProofRequest\x1a .samurai.api.v1.GetProofResponse0\x01\x12J\n" +
	"\aGetInfo\x12\x1e.samurai.api.v1.GetInfoRequest\x1a\x1f.samurai.api.v1.GetInfoResponseB:Z8github.com/nepal80m/samurai/api/proto/samurai/v1;proofpbb\x06proto3"

var (
	file_api_proto_samurai_v1_proof_service_proto_rawDescOnce sync.Once
	file_api_proto_samurai_v1_proof_service_proto_rawDescData []byte
)

func file_api_proto_samurai_v1_proof_service_proto_rawDescGZIP() []byte {
	file_api_proto_samurai_v1_proof_service_proto_rawDescOnce.Do(func() {
		file_api_proto_samurai_v1_proof_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_samurai_v1_proof_service_proto_rawDesc), len(file_api_proto_samurai_v1_proof_service_proto_rawDesc)))
	})
	return file_api_proto_samurai_v1_proof_service_proto_rawDescData
}

var file_api_proto_samurai_v1_proof_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_samurai_v1_proof_service_proto_goTypes = []any{
	(*GetProofRequest)(nil),  // 0: samurai.api.v1.GetProofRequest
	(*GetProofResponse)(nil), // 1: samurai.api.v1.GetProofResponse
	(*RangeProof)(nil),       // 2: samurai.api.v1.RangeProof
	(*BlockRange)(nil),       // 3: samurai.api.v1.BlockRange
	(*BalanceInfo)(nil),      // 4: samurai.api.v1.BalanceInfo
	(*GetInfoRequest)(nil),   // 5: samurai.api.v1.GetInfoRequest
	(*GetInfoResponse)(nil),  // 6: samurai.api.v1.GetInfoResponse
}
var file_api_proto_samurai_v1_proof_service_proto_depIdxs = []int32{
	2, // 0: samurai.api.v1.GetProofResponse.range_proofs:type_name -> samurai.api.v1.RangeProof
	4, // 1: samurai.api.v1.GetProofResponse.balance_infos:type_name -> samurai.api.v1.BalanceInfo
	3, // 2: samurai.api.v1.RangeProof.block_range:type_name -> samurai.api.v1.BlockRange
	0, // 3: samurai.api.v1.ProofService.GetProof:input_type -> samurai.api.v1.GetProofRequest
	0, // 4: samurai.api.v1.ProofService.GetProofStream:input_type -> samurai.api.v1.GetProofRequest
	0, // 5: samurai.api.v1.ProofService.GetOldProofStream:input_type -> samurai.api.v1.GetProofRequest
	5, // 6: samurai.api.v1.ProofService.GetInfo:input_type -> samurai.api.v1.GetInfoRequest
	1, // 7: samurai.api.v1.ProofService.GetProof:output_type -> samurai.api.v1.GetProofResponse
	1, // 8: samurai.api.v1.ProofService.GetProofStream:output_type -> samurai.api.v1.GetProofResponse
	1, // 9: samurai.api.v1.ProofService.GetOldProofStream:output_type -> samurai.api.v1.GetProofResponse
	6, // 10: samurai.api.v1.ProofService.GetInfo:output_type -> samurai.api.v1.GetInfoResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_samurai_v1_proof_service_proto_init() }
func file_api_proto_samurai_v1_proof_service_proto_init() {
	if File_api_proto_samurai_v1_proof_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_samurai_v1_proof_service_proto_rawDesc), len(file_api_proto_samurai_v1_proof_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_samurai_v1_proof_service_proto_goTypes,
		DependencyIndexes: file_api_proto_samurai_v1_proof_service_proto_depIdxs,
		MessageInfos:      file_api_proto_samurai_v1_proof_service_proto_msgTypes,
	}.Build()
	File_api_proto_samurai_v1_proof_service_proto = out.File
	file_api_proto_samurai_v1_proof_service_proto_goTypes = nil
	file_api_proto_samurai_v1_proof_service_proto_depIdxs = nil
}
